# Create AkinaySau(akinaysau@gmail.com)
services:
    Sau\WP\Framework\Bundle\CarbonBundle\Twig\:
        resource: '../../Twig/*'
    carbon.container_loader:
        class: Sau\WP\Framework\Bundle\CarbonBundle\Loader\CarbonLoader
        public: true
