<?php
/**
 * Created by PhpStorm.
 * User: AkinaySau(akinaysau@gmail.com)
 * Date: 18.12.18
 * Time: 16:12
 *
 * @package wp-framework
 */

namespace Sau\WP\Framework\Bundle\AdminBundle;


use Sau\WP\Framework\Bundle\AdminBundle\Admin\CollectionAdmin;
use Sau\WP\Framework\Bundle\AdminBundle\DependencyInjection\Compiler\AdminPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class AdminBundle extends Bundle
{

    public function boot()
    {
        if ($this->container->has('admin')) {
            $this->container->get('admin');
        }

    }

    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new AdminPass());


    }


}
